//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentManagementBackend.Demo.App_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentManagementBackend.Demo.App_Resources.GlobalContent", typeof(GlobalContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слeдующий век.
        /// </summary>
        public static string BsDatetimePicker_NextCentury {
            get {
                return ResourceManager.GetString("BsDatetimePicker_NextCentury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слeдующая декада.
        /// </summary>
        public static string BsDatetimePicker_NextDecade {
            get {
                return ResourceManager.GetString("BsDatetimePicker_NextDecade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слeдующий месяц.
        /// </summary>
        public static string BsDatetimePicker_NextMonth {
            get {
                return ResourceManager.GetString("BsDatetimePicker_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слeдующий год.
        /// </summary>
        public static string BsDatetimePicker_NextYear {
            get {
                return ResourceManager.GetString("BsDatetimePicker_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий век.
        /// </summary>
        public static string BsDatetimePicker_PrevCentury {
            get {
                return ResourceManager.GetString("BsDatetimePicker_PrevCentury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущая декада.
        /// </summary>
        public static string BsDatetimePicker_PrevDecade {
            get {
                return ResourceManager.GetString("BsDatetimePicker_PrevDecade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий месяц.
        /// </summary>
        public static string BsDatetimePicker_PrevMonth {
            get {
                return ResourceManager.GetString("BsDatetimePicker_PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий год.
        /// </summary>
        public static string BsDatetimePicker_PrevYear {
            get {
                return ResourceManager.GetString("BsDatetimePicker_PrevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите декаду.
        /// </summary>
        public static string BsDatetimePicker_SelectDecade {
            get {
                return ResourceManager.GetString("BsDatetimePicker_SelectDecade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите месяц.
        /// </summary>
        public static string BsDatetimePicker_SelectMonth {
            get {
                return ResourceManager.GetString("BsDatetimePicker_SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите год.
        /// </summary>
        public static string BsDatetimePicker_SelectYear {
            get {
                return ResourceManager.GetString("BsDatetimePicker_SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена категория.
        /// </summary>
        public static string Categories_Index_NotFound {
            get {
                return ResourceManager.GetString("Categories_Index_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string Categories_List_Title {
            get {
                return ResourceManager.GetString("Categories_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Ckeditor_Image {
            get {
                return ResourceManager.GetString("Ckeditor_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение во всю ширину.
        /// </summary>
        public static string Ckeditor_ImageFullWidth {
            get {
                return ResourceManager.GetString("Ckeditor_ImageFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение слева.
        /// </summary>
        public static string Ckeditor_ImageLeft {
            get {
                return ResourceManager.GetString("Ckeditor_ImageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение справа.
        /// </summary>
        public static string Ckeditor_ImageRight {
            get {
                return ResourceManager.GetString("Ckeditor_ImageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подзаголовок.
        /// </summary>
        public static string Ckeditor_Subtitle {
            get {
                return ResourceManager.GetString("Ckeditor_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; уже используется..
        /// </summary>
        public static string CommentAuthPipeline_DuplicateEmail {
            get {
                return ResourceManager.GetString("CommentAuthPipeline_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введён Email.
        /// </summary>
        public static string CommentAuthPipeline_EmailBadFormed {
            get {
                return ResourceManager.GetString("CommentAuthPipeline_EmailBadFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Email.
        /// </summary>
        public static string CommentAuthPipeline_EmailRequired {
            get {
                return ResourceManager.GetString("CommentAuthPipeline_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Имя.
        /// </summary>
        public static string CommentAuthPipeline_NameRequired {
            get {
                return ResourceManager.GetString("CommentAuthPipeline_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string CommentAuthPipeline_PasswordRequired {
            get {
                return ResourceManager.GetString("CommentAuthPipeline_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при авторизации..
        /// </summary>
        public static string Common_AuthError {
            get {
                return ResourceManager.GetString("Common_AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены?.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Common_Download {
            get {
                return ResourceManager.GetString("Common_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Common_Paging_First {
            get {
                return ResourceManager.GetString("Common_Paging_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в начало.
        /// </summary>
        public static string Common_Paging_First_Title {
            get {
                return ResourceManager.GetString("Common_Paging_First_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец.
        /// </summary>
        public static string Common_Paging_Last {
            get {
                return ResourceManager.GetString("Common_Paging_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в конец.
        /// </summary>
        public static string Common_Paging_Last_Title {
            get {
                return ResourceManager.GetString("Common_Paging_Last_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След.
        /// </summary>
        public static string Common_Paging_Next {
            get {
                return ResourceManager.GetString("Common_Paging_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к следующей странице.
        /// </summary>
        public static string Common_Paging_Next_Title {
            get {
                return ResourceManager.GetString("Common_Paging_Next_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к странице {0}.
        /// </summary>
        public static string Common_Paging_Page_Title {
            get {
                return ResourceManager.GetString("Common_Paging_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пред.
        /// </summary>
        public static string Common_Paging_Prev {
            get {
                return ResourceManager.GetString("Common_Paging_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к предыдущей странице.
        /// </summary>
        public static string Common_Paging_Prev_Title {
            get {
                return ResourceManager.GetString("Common_Paging_Prev_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Common_PostComments {
            get {
                return ResourceManager.GetString("Common_PostComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотры.
        /// </summary>
        public static string Common_PostViews {
            get {
                return ResourceManager.GetString("Common_PostViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорее всего, это не та страница, которую вы ожидали увидеть. Мы попробуем разобраться что же пошло не так при выполнении запроса..
        /// </summary>
        public static string Error_Internal_Description {
            get {
                return ResourceManager.GetString("Error_Internal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла внутренняя ошибка.
        /// </summary>
        public static string Error_Internal_Message {
            get {
                return ResourceManager.GetString("Error_Internal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя ошибка.
        /// </summary>
        public static string Error_Internal_Title {
            get {
                return ResourceManager.GetString("Error_Internal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот адрес удалён, стёрт, закопан или поломан. Возможно, что материалы по этому адресу более не доступны..
        /// </summary>
        public static string Error_NoSuchPage_Description {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Главную: Жмите сюда и мы вернём вас на главную страницу.
        /// </summary>
        public static string Error_NoSuchPage_Home {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти то, что вы искали.
        /// </summary>
        public static string Error_NoSuchPage_Message {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К Поиску: Найдите нужную страницу через поиск.
        /// </summary>
        public static string Error_NoSuchPage_SearchMessage {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_SearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Но не волнуйтесь, попробуйте вернуться:.
        /// </summary>
        public static string Error_NoSuchPage_Suggestion {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string Error_NoSuchPage_Title {
            get {
                return ResourceManager.GetString("Error_NoSuchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить из Url.
        /// </summary>
        public static string ImageUploader_DownloadFromUrl {
            get {
                return ResourceManager.GetString("ImageUploader_DownloadFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только изображения в формате jpg, png и gif..
        /// </summary>
        public static string ImageUploader_FormatException {
            get {
                return ResourceManager.GetString("ImageUploader_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите изображение для загрузки.
        /// </summary>
        public static string ImageUploader_NoImageDropZone {
            get {
                return ResourceManager.GetString("ImageUploader_NoImageDropZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить изображение.
        /// </summary>
        public static string ImageUploader_Restore {
            get {
                return ResourceManager.GetString("ImageUploader_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить из файла.
        /// </summary>
        public static string ImageUploader_UploadFromFile {
            get {
                return ResourceManager.GetString("ImageUploader_UploadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любое использование материалов допускается только с согласия редакции..
        /// </summary>
        public static string Layout_CopyWarning {
            get {
                return ResourceManager.GetString("Layout_CopyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи.
        /// </summary>
        public static string Menu_Posts {
            get {
                return ResourceManager.GetString("Menu_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Menu_PostsAdd {
            get {
                return ResourceManager.GetString("Menu_PostsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Menu_PostsEditList {
            get {
                return ResourceManager.GetString("Menu_PostsEditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Menu_Users {
            get {
                return ResourceManager.GetString("Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить материал.
        /// </summary>
        public static string Post_Add_Title {
            get {
                return ResourceManager.GetString("Post_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья успешно удалена.
        /// </summary>
        public static string Post_Delete_Message {
            get {
                return ResourceManager.GetString("Post_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья удалена.
        /// </summary>
        public static string Post_Delete_Title {
            get {
                return ResourceManager.GetString("Post_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить статью.
        /// </summary>
        public static string Post_Edit_AddPost {
            get {
                return ResourceManager.GetString("Post_Edit_AddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение в списке.
        /// </summary>
        public static string Post_Edit_ImageTitle {
            get {
                return ResourceManager.GetString("Post_Edit_ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр.
        /// </summary>
        public static string Post_Edit_PreviewPostButton {
            get {
                return ResourceManager.GetString("Post_Edit_PreviewPostButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр.
        /// </summary>
        public static string Post_Edit_PreviewPostTitle {
            get {
                return ResourceManager.GetString("Post_Edit_PreviewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование статьи.
        /// </summary>
        public static string Post_Edit_Title {
            get {
                return ResourceManager.GetString("Post_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Post_Edit_UpdateNonceModalTitle {
            get {
                return ResourceManager.GetString("Post_Edit_UpdateNonceModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено.
        /// </summary>
        public static string Post_Full_AddDate {
            get {
                return ResourceManager.GetString("Post_Full_AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти анонимно.
        /// </summary>
        public static string Post_Full_AuthLocalAccount {
            get {
                return ResourceManager.GetString("Post_Full_AuthLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти через социальную сеть.
        /// </summary>
        public static string Post_Full_AuthSocialAccount {
            get {
                return ResourceManager.GetString("Post_Full_AuthSocialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Post_Full_CommentEmail {
            get {
                return ResourceManager.GetString("Post_Full_CommentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Post_Full_Comments {
            get {
                return ResourceManager.GetString("Post_Full_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Post_Full_CommentUserName {
            get {
                return ResourceManager.GetString("Post_Full_CommentUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставьте комментарий.
        /// </summary>
        public static string Post_Full_DefaultInputText {
            get {
                return ResourceManager.GetString("Post_Full_DefaultInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string Post_Full_Reply {
            get {
                return ResourceManager.GetString("Post_Full_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смотреть дальше.
        /// </summary>
        public static string Post_Full_SimilarPosts {
            get {
                return ResourceManager.GetString("Post_Full_SimilarPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья не найдена.
        /// </summary>
        public static string Post_Index_PostNotFoundTitle {
            get {
                return ResourceManager.GetString("Post_Index_PostNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Post_List_Edit {
            get {
                return ResourceManager.GetString("Post_List_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти.
        /// </summary>
        public static string Post_List_More {
            get {
                return ResourceManager.GetString("Post_List_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое.
        /// </summary>
        public static string Post_List_New {
            get {
                return ResourceManager.GetString("Post_List_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ещё.
        /// </summary>
        public static string Post_List_NextList {
            get {
                return ResourceManager.GetString("Post_List_NextList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Post_List_Title {
            get {
                return ResourceManager.GetString("Post_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный список статей.
        /// </summary>
        public static string Post_Moderation_Title {
            get {
                return ResourceManager.GetString("Post_Moderation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный список.
        /// </summary>
        public static string Post_Moderation_TitleShort {
            get {
                return ResourceManager.GetString("Post_Moderation_TitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Везде.
        /// </summary>
        public static string Search_Index_AllCategories {
            get {
                return ResourceManager.GetString("Search_Index_AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Search_Index_Find {
            get {
                return ResourceManager.GetString("Search_Index_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, ничего не найдено. Попробуйте переформулировать свой запрос или поискать что-то другое..
        /// </summary>
        public static string Search_Index_NoMatchFound {
            get {
                return ResourceManager.GetString("Search_Index_NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search_Index_Title {
            get {
                return ResourceManager.GetString("Search_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы искали.
        /// </summary>
        public static string Search_Index_YouSearched {
            get {
                return ResourceManager.GetString("Search_Index_YouSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вернуться.
        /// </summary>
        public static string Shared_Error_BackText {
            get {
                return ResourceManager.GetString("Shared_Error_BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при выполнении запроса. Попробуйте .
        /// </summary>
        public static string Shared_Error_Message1 {
            get {
                return ResourceManager.GetString("Shared_Error_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на главную страницу..
        /// </summary>
        public static string Shared_Error_Message2 {
            get {
                return ResourceManager.GetString("Shared_Error_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск.
        /// </summary>
        public static string Shared_Layout_SearchDefault {
            get {
                return ResourceManager.GetString("Shared_Layout_SearchDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string SidebarLayout_Comments {
            get {
                return ResourceManager.GetString("SidebarLayout_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярное.
        /// </summary>
        public static string SidebarLayout_PopularPosts {
            get {
                return ResourceManager.GetString("SidebarLayout_PopularPosts", resourceCulture);
            }
        }
    }
}
