//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatana.Contents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanatana.Contents.Resources.ContentsMessages", typeof(ContentsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария не может быть пустым..
        /// </summary>
        public static string Comment_ContentEmpty {
            get {
                return ResourceManager.GetString("Comment_ContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для доступа требуются дополнительные права..
        /// </summary>
        public static string Common_AuthorizationRequired {
            get {
                return ResourceManager.GetString("Common_AuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория не найдена.
        /// </summary>
        public static string Common_CategoryNotFound {
            get {
                return ResourceManager.GetString("Common_CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указана дата {0}.
        /// </summary>
        public static string Common_DateParseException {
            get {
                return ResourceManager.GetString("Common_DateParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время обработки запроса произошло исключение..
        /// </summary>
        public static string Common_ProcessingError {
            get {
                return ResourceManager.GetString("Common_ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден..
        /// </summary>
        public static string Common_UserNotFound {
            get {
                return ResourceManager.GetString("Common_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Content_AuthorName {
            get {
                return ResourceManager.GetString("Content_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Content_CategoryId {
            get {
                return ResourceManager.GetString("Content_CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество комментариев.
        /// </summary>
        public static string Content_CommentsCount {
            get {
                return ResourceManager.GetString("Content_CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст материала не может быть пустым..
        /// </summary>
        public static string Content_FullContentEmpty {
            get {
                return ResourceManager.GetString("Content_FullContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный текст.
        /// </summary>
        public static string Content_FullText {
            get {
                return ResourceManager.GetString("Content_FullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Материал по этому адресу не существует или был удален..
        /// </summary>
        public static string Content_NotFound {
            get {
                return ResourceManager.GetString("Content_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время публикации должно быть уникально. Попробуйте изменить время публикации на другое..
        /// </summary>
        public static string Content_PublishTimeIsNotUnique {
            get {
                return ResourceManager.GetString("Content_PublishTimeIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время публикации.
        /// </summary>
        public static string Content_PublishTimeUtc {
            get {
                return ResourceManager.GetString("Content_PublishTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткий текст.
        /// </summary>
        public static string Content_ShortText {
            get {
                return ResourceManager.GetString("Content_ShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показано материалов: {0} из {1}.
        /// </summary>
        public static string Content_Shown {
            get {
                return ResourceManager.GetString("Content_Shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Content_Title {
            get {
                return ResourceManager.GetString("Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название материала не может быть пустым..
        /// </summary>
        public static string Content_TitleEmpty {
            get {
                return ResourceManager.GetString("Content_TitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть материал с таким адресом. Измените адрес материала или заголовок, если адрес составляется автоматически..
        /// </summary>
        public static string Content_UrlIsNotUnique {
            get {
                return ResourceManager.GetString("Content_UrlIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество просмотров.
        /// </summary>
        public static string Content_ViewsCount {
            get {
                return ResourceManager.GetString("Content_ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержимое было изменено с момента получения кем-то другим. Ваше действие их отменит. Уверены, что хотите продолжить?.
        /// </summary>
        public static string Content_WrongUpdateNonce {
            get {
                return ResourceManager.GetString("Content_WrongUpdateNonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный формат изображения..
        /// </summary>
        public static string Image_FormatException {
            get {
                return ResourceManager.GetString("Image_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верно сформирован адрес {0}.
        /// </summary>
        public static string Image_InvalidUrl {
            get {
                return ResourceManager.GetString("Image_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение с названием {0} уже сохранено..
        /// </summary>
        public static string Image_NameInUse {
            get {
                return ResourceManager.GetString("Image_NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при передаче изображения..
        /// </summary>
        public static string Image_ReceiveException {
            get {
                return ResourceManager.GetString("Image_ReceiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при сохранении изображения..
        /// </summary>
        public static string Image_SaveException {
            get {
                return ResourceManager.GetString("Image_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер изображения не должен превышать {0} байт..
        /// </summary>
        public static string Image_SizeExceeeded {
            get {
                return ResourceManager.GetString("Image_SizeExceeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник изображения не указан..
        /// </summary>
        public static string Image_SourceNotSpecified {
            get {
                return ResourceManager.GetString("Image_SourceNotSpecified", resourceCulture);
            }
        }
    }
}
